import Homecontainer from "@/container/homecontainer";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Ecommerce Product Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homecontainer />
    </>
  );
};

export default Home;
